Repository BAECHOOs/Spring-toyproject, pull requests merged in 2021-02, with the labels that each got.

#10 Add Spring Security document
  share knowhow/Spring Security.md
Labels: Security

#12 Sangjin
  share knowhow/Thymeleaf정리.md
  spring-team/src/main/java/toyproject/springteam/HomeController.java
  spring-team/src/main/resources/static/css/style.css
  spring-team/src/main/resources/static/img/logo1.png
  spring-team/src/main/resources/static/img/spring.png
  spring-team/src/main/resources/templates/fragments/footer.html
  spring-team/src/main/resources/templates/fragments/header.html
  spring-team/src/main/resources/templates/fragments/layout.html
  spring-team/src/main/resources/templates/home.html
Labels: FrontEnd

#19 Create like domain, Edit sql Setting, Add documents
  share knowhow/IntelliJ DB Navigator에서 DB 작업하기.md
  share knowhow/도메인 클래스 관련 참고사항.md
  spring-team/build.gradle
  spring-team/src/main/java/toyproject/springteam/controller/LikeApiController.java
  spring-team/src/main/java/toyproject/springteam/controller/dto/LikeSaveRequestDto.java
  spring-team/src/main/java/toyproject/springteam/domain/BaseTimeEntity.java
  spring-team/src/main/java/toyproject/springteam/domain/Like.java
  spring-team/src/main/java/toyproject/springteam/repository/LikeRepository.java
  spring-team/src/main/java/toyproject/springteam/service/LikeService.java
  spring-team/src/main/resources/application.properties
Labels: Database, request, 혜원

#22 Update Login page & Database
  spring-team/build.gradle
  spring-team/sql/ddl.sql
  spring-team/src/main/java/toyproject/springteam/config/WebSecurityConfig.java
  spring-team/src/main/java/toyproject/springteam/controller/AccountController.java
  spring-team/src/main/java/toyproject/springteam/controller/BoardController.java
  spring-team/src/main/java/toyproject/springteam/domain/Role.java
  spring-team/src/main/java/toyproject/springteam/domain/User.java
  spring-team/src/main/java/toyproject/springteam/repository/UserRepository.java
  spring-team/src/main/java/toyproject/springteam/service/UserService.java
  spring-team/src/main/resources/application.properties
  spring-team/src/main/resources/static/css/signin.css
  spring-team/src/main/resources/static/css/style.css
  spring-team/src/main/resources/static/css/style2.css
  spring-team/src/main/resources/static/footer.html
  spring-team/src/main/resources/static/header.html
  spring-team/src/main/resources/static/home.html
  spring-team/src/main/resources/static/img/logo2.PNG
  spring-team/src/main/resources/static/img/logo3.PNG
  spring-team/src/main/resources/static/index.html
  spring-team/src/main/resources/static/join.html
  spring-team/src/main/resources/static/login.html
  spring-team/src/main/resources/templates/account/join.html
  spring-team/src/main/resources/templates/account/login.html
  spring-team/src/main/resources/templates/board/board_gallery.html
  spring-team/src/main/resources/templates/board/board_list.html
  spring-team/src/main/resources/templates/board/board_read.html
  spring-team/src/main/resources/templates/fragments/footer.html
  spring-team/src/main/resources/templates/fragments/header.html
  spring-team/src/main/resources/templates/fragments/headerbar.html
  spring-team/src/main/resources/templates/fragments/layout.html
  spring-team/src/main/resources/templates/home.html
  spring-team/src/main/resources/templates/mypage.html
Labels: Database, FrontEnd

#24 Set configure properties
  spring-team/.gitignore
  spring-team/src/main/java/toyproject/springteam/config/AppConfig.java
  spring-team/src/main/resources/application.properties
Labels: Database

#27 Change HeaderBar display when logged in
  spring-team/src/main/java/toyproject/springteam/config/WebSecurityConfig.java
  spring-team/src/main/java/toyproject/springteam/controller/AccountController.java
  spring-team/src/main/java/toyproject/springteam/controller/HomeController.java
  spring-team/src/main/java/toyproject/springteam/controller/dto/UserResponseDto.java
  spring-team/src/main/java/toyproject/springteam/domain/User.java
  spring-team/src/main/java/toyproject/springteam/service/UserService.java
  spring-team/src/main/resources/templates/fragments/headerbar.html
Labels: FrontEnd, Security

#35 Create Main home page
  images/Home logo/대문로고_초록.png
  images/Home logo/대문로고_파랑.png
  images/Logo with project/color_logo_transparent.png
  images/Logo with project/color_logo_with_background.png
  images/Logo with project/dark_logo_transparent.png
  images/Logo with project/white_logo_transparent.png
  images/Logo/color_logo_transparent.png
  images/Logo/color_logo_with_background.png
  images/Logo/dark_logo_transparent.png
  images/Logo/white_logo_transparent.png
  share knowhow/[Spring] 서버 재시작하지 않고 view 변경 확인하기.md
  spring-team/build.gradle
  spring-team/sql/ddl.sql
  spring-team/sql/dml_product.sql
  spring-team/src/main/java/toyproject/springteam/SpringTeamApplication.java
  spring-team/src/main/java/toyproject/springteam/controller/BoardController.java
  spring-team/src/main/java/toyproject/springteam/controller/HomeController.java
  spring-team/src/main/java/toyproject/springteam/controller/dto/ProductListResponseDto.java
  spring-team/src/main/java/toyproject/springteam/domain/Product.java
  spring-team/src/main/java/toyproject/springteam/repository/ProductRepository.java
  spring-team/src/main/java/toyproject/springteam/repository/UserRepository.java
  spring-team/src/main/java/toyproject/springteam/service/ProductService.java
  spring-team/src/main/resources/static/css/home.css
  spring-team/src/main/resources/static/css/product_list.css
  spring-team/src/main/resources/static/css/style.css
  spring-team/src/main/resources/static/img/homelogo_blue.png
  spring-team/src/main/resources/static/img/homelogo_green.png
  spring-team/src/main/resources/templates/board/gallery.html
  spring-team/src/main/resources/templates/board/list.html
  spring-team/src/main/resources/templates/board/read.html
  spring-team/src/main/resources/templates/home.html
Labels: Database, FrontEnd

#44 Rename detail page and passing by product_id
  spring-team/src/main/java/toyproject/springteam/controller/BoardController.java
  spring-team/src/main/java/toyproject/springteam/repository/ProductRepository.java
  spring-team/src/main/java/toyproject/springteam/service/ProductService.java
  spring-team/src/main/resources/static/css/detail.css
  spring-team/src/main/resources/templates/board/detail.html
  spring-team/src/main/resources/templates/fragments/headerbar.html
  spring-team/src/main/resources/templates/home.html
Labels: Database, FrontEnd

#51 Upload Page & error page
  spring-team/src/main/java/toyproject/springteam/controller/AccountController.java
  spring-team/src/main/java/toyproject/springteam/controller/BoardController.java
  spring-team/src/main/java/toyproject/springteam/controller/HomeController.java
  spring-team/src/main/java/toyproject/springteam/controller/ProductController.java
  spring-team/src/main/resources/application.properties
  spring-team/src/main/resources/static/css/error.css
  spring-team/src/main/resources/static/css/upload.css
  spring-team/src/main/resources/static/js/productPrice.js
  spring-team/src/main/resources/templates/board/detail.html
  spring-team/src/main/resources/templates/board/list.html
  spring-team/src/main/resources/templates/board/upload.html
  spring-team/src/main/resources/templates/error.html
  spring-team/src/main/resources/templates/fragments/headerbar.html
  spring-team/src/main/resources/templates/products/new.html
Labels: FrontEnd, bug

#52 create view count and like count
  spring-team/src/main/resources/static/css/fontello-embedded.css
  spring-team/src/main/resources/static/css/product_list.css
  spring-team/src/main/resources/templates/home.html
Labels: FrontEnd
